# Generated by Django 5.0.3 on 2024-04-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_categories_slug_remove_products_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('id',), 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
